dataset: 'synthetic'

data:
  downsample: 1
  sc_factor: 1
  translation: 0
  num_workers: 4

mapping:
  sample: 2048
  first_mesh: True
  iters: 10
  cur_frame_iters: 0
  lr_embed: 0.001
  lr_decoder: 0.01
  lr_rot: 0.001
  lr_trans: 0.001
  keyframe_every: 5
  map_every: 5
  n_pixels: 0.05
  first_iters: 200
  optim_cur: True
  min_pixels_cur: 100
  map_accum_step: 1
  pose_accum_step: 5
  map_wait_step: 0
  filter_depth: False

tracking:
  iter: 10
  sample: 1024
  pc_samples: 40960
  lr_rot: 0.001
  lr_trans: 0.001
  ignore_edge_W: 20
  ignore_edge_H: 20
  iter_point: 0
  wait_iters: 100
  const_speed: True
  best: True

grid:
  enc: 'HashGrid'
  tcnn_encoding: True
  hash_size: 16
  voxel_color: 0.08
  voxel_sdf: 0.01
  oneGrid: True

pos:
  enc: 'OneBlob'
  n_bins: 16

decoder:
  geo_feat_dim: 15
  hidden_dim: 32
  num_layers: 2
  num_layers_color: 2
  hidden_dim_color: 32
  tcnn_network: False

cam:
  H: 480
  W: 640
  fx: 554.2562584220408
  fy: 554.2562584220408
  cx: 320
  cy: 240
  png_depth_scale: 1000. #for depth image in png format
  crop_edge: 0
  near: 0
  far: 4
  depth_trunc: 100.

training:
  rgb_weight: 5.0
  depth_weight: 0.1
  sdf_weight: 1000
  fs_weight: 10
  eikonal_weight: 0
  smooth_weight: 0.00001
  smooth_pts: 32
  smooth_vox: 0.1
  smooth_margin: 0.05
  #n_samples: 256
  n_samples_d: 32
  range_d: 0.1
  n_range_d: 11
  n_importance: 0
  perturb: 1
  white_bkgd: False
  trunc: 0.1
  rot_rep: 'axis_angle'
  rgb_missing: 0.05

mesh:
  resolution: 512
  render_color: False
  vis: 500
  voxel_eval: 0.05
  voxel_final: 0.02
  visualisation: False
  